spring:
  application:
    name: RetailRewardsTask
  profiles:
    active: devEmbedded
  mvc:
    format:
      date: iso

server:
  servlet:
    context-path: /
  port: 8080
  error:
    include-stacktrace: never


#We set old matcher so that swagger works
spring.mvc.pathmatch.matching-strategy: ant_path_matcher
