spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  data:
    mongodb:
      port: 27017
      database: retailer
      host: localhost

server:
  error:
    include-stacktrace: never
    include-message: always
